
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class Ventanas extends javax.swing.JFrame {

    /**
     * Creates new form Ventanas
     */
    public Ventanas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblNoControl = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        txtNoC = new javax.swing.JTextField();
        txtSex = new javax.swing.JTextField();
        txtNomb = new javax.swing.JTextField();
        txtCar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCalculo = new javax.swing.JLabel();
        lblAlgebra = new javax.swing.JLabel();
        lblProbabilidad = new javax.swing.JLabel();
        lblContabilidad = new javax.swing.JLabel();
        lblPOO = new javax.swing.JLabel();
        lblQuimica = new javax.swing.JLabel();
        txtPoo = new javax.swing.JTextField();
        txtAlg = new javax.swing.JTextField();
        txtPro = new javax.swing.JTextField();
        txtQui = new javax.swing.JTextField();
        txtCon = new javax.swing.JTextField();
        txtCal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblPromedio = new javax.swing.JLabel();
        lblAcreditar = new javax.swing.JLabel();
        lblAcr = new javax.swing.JLabel();
        lblProm = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOp = new javax.swing.JTextArea();
        lblOpinion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Integral de Información ");
        jLabel1.setOpaque(true);

        lblNombre.setBackground(new java.awt.Color(0, 102, 153));
        lblNombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("Nombre:");
        lblNombre.setOpaque(true);

        lblNoControl.setBackground(new java.awt.Color(0, 102, 153));
        lblNoControl.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblNoControl.setForeground(new java.awt.Color(255, 255, 255));
        lblNoControl.setText("No. de Control:");
        lblNoControl.setOpaque(true);

        lblSexo.setBackground(new java.awt.Color(0, 102, 153));
        lblSexo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblSexo.setForeground(new java.awt.Color(255, 255, 255));
        lblSexo.setText("Sexo (F/M):");
        lblSexo.setOpaque(true);

        lblCarrera.setBackground(new java.awt.Color(0, 102, 153));
        lblCarrera.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblCarrera.setForeground(new java.awt.Color(255, 255, 255));
        lblCarrera.setText("Carrera:");
        lblCarrera.setOpaque(true);

        txtNoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoCActionPerformed(evt);
            }
        });

        txtSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexActionPerformed(evt);
            }
        });

        txtNomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombActionPerformed(evt);
            }
        });

        txtCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarActionPerformed(evt);
            }
        });
        txtCar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATOS DEL ESTUDIANTE");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PROMEDIO DE MATERIAS");

        lblCalculo.setBackground(new java.awt.Color(204, 204, 204));
        lblCalculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCalculo.setForeground(new java.awt.Color(0, 102, 153));
        lblCalculo.setText("CÁLCULO INTEGRAL:");
        lblCalculo.setOpaque(true);

        lblAlgebra.setBackground(new java.awt.Color(204, 204, 204));
        lblAlgebra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlgebra.setForeground(new java.awt.Color(0, 102, 153));
        lblAlgebra.setText("ÁLGEBRA:");
        lblAlgebra.setOpaque(true);

        lblProbabilidad.setBackground(new java.awt.Color(204, 204, 204));
        lblProbabilidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblProbabilidad.setForeground(new java.awt.Color(0, 102, 153));
        lblProbabilidad.setText("PROB. Y ESTADÍSTICA:");
        lblProbabilidad.setOpaque(true);

        lblContabilidad.setBackground(new java.awt.Color(204, 204, 204));
        lblContabilidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblContabilidad.setForeground(new java.awt.Color(0, 102, 153));
        lblContabilidad.setText("CONTABILIDAD");
        lblContabilidad.setOpaque(true);

        lblPOO.setBackground(new java.awt.Color(204, 204, 204));
        lblPOO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPOO.setForeground(new java.awt.Color(0, 102, 153));
        lblPOO.setText("POO:");
        lblPOO.setOpaque(true);

        lblQuimica.setBackground(new java.awt.Color(204, 204, 204));
        lblQuimica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQuimica.setForeground(new java.awt.Color(0, 102, 153));
        lblQuimica.setText("QUÍMICA:");
        lblQuimica.setOpaque(true);

        txtPoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPooActionPerformed(evt);
            }
        });

        txtAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlgActionPerformed(evt);
            }
        });

        txtPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProActionPerformed(evt);
            }
        });

        txtQui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuiActionPerformed(evt);
            }
        });

        txtCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConActionPerformed(evt);
            }
        });
        txtCon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtConKeyPressed(evt);
            }
        });

        txtCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("(0-!00)");

        jButton1.setText("Subir Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblPromedio.setBackground(new java.awt.Color(0, 102, 153));
        lblPromedio.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblPromedio.setForeground(new java.awt.Color(255, 255, 255));
        lblPromedio.setText("Promedio:");
        lblPromedio.setOpaque(true);

        lblAcreditar.setBackground(new java.awt.Color(0, 102, 153));
        lblAcreditar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblAcreditar.setForeground(new java.awt.Color(255, 255, 255));
        lblAcreditar.setText("Acredita:");
        lblAcreditar.setOpaque(true);

        lblAcr.setBackground(new java.awt.Color(255, 255, 255));
        lblAcr.setOpaque(true);

        lblProm.setBackground(new java.awt.Color(255, 255, 255));
        lblProm.setOpaque(true);

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtOp.setColumns(20);
        txtOp.setRows(5);
        txtOp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOpKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtOp);

        lblOpinion.setBackground(new java.awt.Color(0, 102, 153));
        lblOpinion.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblOpinion.setForeground(new java.awt.Color(255, 255, 255));
        lblOpinion.setText("Opinión a del Tec:");
        lblOpinion.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNoControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblOpinion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNoC)
                            .addComponent(txtSex)
                            .addComponent(txtCar)
                            .addComponent(txtNomb)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblCalculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAlgebra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblProbabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblContabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblPOO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblQuimica, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPoo)
                                        .addComponent(txtAlg, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                        .addComponent(txtPro, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                        .addComponent(txtQui, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                        .addComponent(txtCon, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                        .addComponent(txtCal, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                                    .addComponent(lblProm, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAcreditar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAcr, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addGap(3, 3, 3)))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoControl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPOO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlgebra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlg, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuimica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQui, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAcreditar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAcr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOpinion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoCActionPerformed

    private void txtSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexActionPerformed

    private void txtNombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombActionPerformed

    private void txtCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarActionPerformed

    private void txtPooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPooActionPerformed

    private void txtAlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlgActionPerformed

    private void txtProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProActionPerformed

    private void txtQuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuiActionPerformed

    private void txtConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConActionPerformed

    private void txtCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String cal, alg, poo, pro, qui, con;
        float num1, num2, num3, num4, num5, num6;
        double prom;
        boolean acr;
        
        cal = txtCal.getText();
        num1 = Float.parseFloat(cal);
        
        poo = txtPoo.getText();
        num2 = Float.parseFloat(poo);
        
        alg = txtAlg.getText();
        num3 = Float.parseFloat(alg);
        
        pro = txtPro.getText();
        num4 = Float.parseFloat(pro);
        
        qui = txtQui.getText();
        num5 = Float.parseFloat(qui);
        
        con = txtCon.getText();
        num6 = Float.parseFloat(con);
        
        prom = (num1 + num2 + num3 + num4 + num5 + num6)/6;
        lblProm.setText("" + prom);
        
        acr = prom > 70;
        if (prom > 70){
            lblAcr.setText("" + acr);
        } else {
            lblAcr.setText("" + acr);     
    }
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nomb, car, s, sexo, inicio, op;
        int NoC;
        char genero, s1 = 'M', s2 = 'F';
        
        op = txtOp.getText();
        nomb = txtNomb.getText();
        car = txtCar.getText();
        s = txtSex.getText();
        NoC = Integer.parseInt(txtNoC.getText());
        
        genero = s.charAt(0);
        
        if (genero == s1){
            sexo = "Tu genero seleccionado es Masculino";
        }  else if (genero == s2){
            sexo = "Tu genero seleccionado es Femenino";
        }
        else {
            sexo = "Dato erróneo (vuelva a intentar)";
                   }
        
        inicio = "Bienvenido " + nomb+ "\n"+ sexo + "\nTu numero de control es " + NoC + 
                "\nEstas en la carrera de " + car + "\nTu opinión: " + op + " :ha sido enviada a control escolar, gracias.";
        JOptionPane.showMessageDialog(null, inicio);
        
        txtNomb.setText("");
        txtNoC.setText("");
        txtCar.setText("");
        txtSex.setText("");
        txtOp.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCarKeyPressed

    private void txtConKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER){
            jButton2ActionPerformed(null);
        }
    }//GEN-LAST:event_txtConKeyPressed

    private void txtOpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOpKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER){
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_txtOpKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAcr;
    private javax.swing.JLabel lblAcreditar;
    private javax.swing.JLabel lblAlgebra;
    private javax.swing.JLabel lblCalculo;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblContabilidad;
    private javax.swing.JLabel lblNoControl;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOpinion;
    private javax.swing.JLabel lblPOO;
    private javax.swing.JLabel lblProbabilidad;
    private javax.swing.JLabel lblProm;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblQuimica;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JTextField txtAlg;
    private javax.swing.JTextField txtCal;
    private javax.swing.JTextField txtCar;
    private javax.swing.JTextField txtCon;
    private javax.swing.JTextField txtNoC;
    private javax.swing.JTextField txtNomb;
    private javax.swing.JTextArea txtOp;
    private javax.swing.JTextField txtPoo;
    private javax.swing.JTextField txtPro;
    private javax.swing.JTextField txtQui;
    private javax.swing.JTextField txtSex;
    // End of variables declaration//GEN-END:variables
}
